### ISSUE TITLE
libwkhtmltox.dll could not be opened in MVC Core 2 projects

### ISSUE THREAD

**Issue by Ahmed-Raouf** [rdvojmoc/DinkToPdf#25] opened 2018-01-26 12:57 UTC
Hi,

I created new web Mvc Core 2 project and installed DintoPdf from NuGet. Then I copied the libwkhtmltox.dll on the root folder and also on the path of nuget packages in system driver.

When I run the application, the following problem is issued:

Metadata file 'C:\Users\a.fetouh\.nuget\packages\dinktopdf/1.0.8\lib/netstandard1.6/libwkhtmltox.dll' could not be opened -- PE image doesn't contain managed metadata.

Any body can help me?

**Comment by jfarinhote** [comment] 2018-01-26 13:17
There are 2 versions of libwkhtmltox.dll. Are you using the right one? 32 bits or 64?

**Comment by rdvojmoc** [comment] 2018-01-26 13:31
Can you provide reproducible project to take a look?

**Comment by Ahmed-Raouf** [comment] 2018-01-26 15:42
I use 64 bit version. For my projects in Cor 1.0 there are no problems. But in Core 2 I have theis issue.

**Comment by Ahmed-Raouf** [comment] 2018-01-26 15:50
There is no need to upload a project. I use Visual Studio 2017 Community edition. I follow the following steps:
- Create new web project. Asp Mvc Core 2 project.
- Install DinkToPdf using NuGet.
- I copied the libraries "libwkhtmltox.dll - libwkhtmltox.dylib - libwkhtmltox.so" to the root folder in the project.
- I copied the same files in the path: 
C:\Users\a.fetouh\.nuget\packages\dinktopdf\1.0.8\lib\netstandard1.6

**Comment by Ahmed-Raouf** [comment] 2018-01-26 15:51
and this code in Startup.cs:

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddSingleton(typeof(IConverter), new SynchronizedConverter(new PdfTools()));
            services.AddMvc();
        }

**Comment by Ahmed-Raouf** [comment] 2018-01-26 15:58
The Error details:

BadImageFormatException: Image is either too small or contains an invalid byte offset or count.
System.Reflection.Throw.ImageTooSmallOrContainsInvalidOffsetOrCount()
System.Reflection.PortableExecutable.PEBinaryReader.ReadNullPaddedUTF8(int byteCount)
System.Reflection.PortableExecutable.SectionHeader..ctor(ref PEBinaryReader reader)
System.Reflection.PortableExecutable.PEHeaders.ReadSectionHeaders(ref PEBinaryReader reader)
System.Reflection.PortableExecutable.PEHeaders..ctor(Stream peStream, int size, bool isLoadedImage)
System.Reflection.PortableExecutable.PEReader..ctor(Stream peStream, PEStreamOptions options, int size)
System.Reflection.PortableExecutable.PEReader..ctor(Stream peStream, PEStreamOptions options)
Microsoft.CodeAnalysis.ModuleMetadata.CreateFromStream(Stream peStream, PEStreamOptions options)
Microsoft.AspNetCore.Mvc.Razor.Compilation.MetadataReferenceFeatureProvider.CreateMetadataReference(string path)
Microsoft.AspNetCore.Mvc.Razor.Compilation.MetadataReferenceFeatureProvider.PopulateFeature(IEnumerable<ApplicationPart> parts, MetadataReferenceFeature feature)
Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature<TFeature>(TFeature feature)
Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorReferenceManager.GetCompilationReferences()
System.Threading.LazyInitializer.EnsureInitializedCore<T>(ref T target, ref bool initialized, ref object syncLock, Func<T> valueFactory)
Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorReferenceManager.get_CompilationReferences()
Microsoft.CodeAnalysis.Razor.CompilationTagHelperFeature.GetDescriptors()
Microsoft.AspNetCore.Razor.Language.DefaultRazorTagHelperBinderPhase.ExecuteCore(RazorCodeDocument codeDocument)
Microsoft.AspNetCore.Razor.Language.RazorEnginePhaseBase.Execute(RazorCodeDocument codeDocument)
Microsoft.AspNetCore.Razor.Language.DefaultRazorEngine.Process(RazorCodeDocument document)
Microsoft.AspNetCore.Razor.Language.RazorTemplateEngine.GenerateCode(RazorCodeDocument codeDocument)
Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CompileAndEmit(string relativePath)
Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CreateCacheEntry(string normalizedPath)
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.RazorPages.Internal.DefaultPageLoader.Load(PageActionDescriptor actionDescriptor)
Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvokerProvider.OnProvidersExecuting(ActionInvokerProviderContext context)
Microsoft.AspNetCore.Mvc.Internal.ActionInvokerFactory.CreateInvoker(ActionContext actionContext)
Microsoft.AspNetCore.Mvc.Internal.MvcAttributeRouteHandler+<>c__DisplayClass12_0.<RouteAsync>b__0(HttpContext c)
Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()

**Comment by jfarinhote** [comment] 2018-01-26 20:41
Please double check if your Mvc project is set up for 64 or 32 bits. I remember having some issues with that.

**Comment by rdvojmoc** [comment] 2018-01-26 21:52
@Ahmed-Raouf, created Asp Mvc Core 2 project, and do rest of the steps that you listed, and documented was converted successfully. Please make sure that you use it with Kestrel not IIS web server.

**Comment by jfarinhote** [comment] 2018-01-26 23:32
I am using IIS web server and it works

**Comment by Ahmed-Raouf** [comment] 2018-01-27 13:01
The project builds in x64. The problem is raised when I run with Kestrel or with IIS Express

**Comment by Ahmed-Raouf** [comment] 2018-01-27 13:07
I uploaded the solution on Google drive:
https://drive.google.com/file/d/1IgKZpLLZfbr8wriWNd1QGvP2oqF1Vuz9/view?usp=sharing

May you take a look please?
Thanks

**Comment by jfarinhote** [comment] 2018-01-27 21:30
I cant run .net core at home. My guess is that you are using a wrong version of _libwkhtmltox_, the 64 bit has 29MB you are using one with 49k

**Comment by Ahmed-Raouf** [comment] 2018-01-28 11:03
I replaced the files as you told with the right files from the source project in git hub. Bit still the problem is exist.
I have a project created in Core 1 and it works with no problem which means that I use the true libraries. The problem only exists when you try to install DinkToPdf in Core 2 projects.

**Comment by Ahmed-Raouf** [comment] 2018-01-28 18:19
Thanks guys. I fixed the problem.
- I downloaded the source code for the DinkToPdf library. Its a Standard .Net class Library project.
- I created a .net core 2 class library new project and copied all the code from the original project to my new project ".Net Core Class library".
- I created a web project in Asp MVC Core 2 as a test project. then added a reference to the class library project.
- Then I built the two projects as 64 bit and copied the libwkhtmlox files into the path:
TestDinkToPdf_WebMvcCore2App\bin\Debug\netcoreapp2.0
For the web project.

It works now.

**Comment by Ahmed-Raouf** [comment] 2018-01-28 18:20
You can download the full solution from the url:

https://drive.google.com/open?id=1SzWP2O-9IdvNlVCug3VhFlA577NX_HN-

**Comment by rdvojmoc** [comment] 2018-01-28 20:53
After taking starting your project this is thrown at application start: `System.InvalidOperationException: Can not find compilation library location for package 'DinkToPdf'`

I took a look at .deps.json and found that there is reference to the` DinkToPdf 1.0.7`:
![image](https://user-images.githubusercontent.com/13537823/35486881-c4dae1b2-0474-11e8-8f1a-664f08d393b7.png)

Deleted directory `/bin` and `/obj`, then compiled and started again and get no error. After trying to convert a file in `Index.cs.html` I get error `BadImageFormatException: Image is either too small or contains an invalid byte offset or count.` which was was caused because wrong `libwkhtmltox` libraries (only 48 kB in size). After replacing the libraries I successfuly converted a file in `Index.cs.html`. Code:
```
    public class IndexModel : PageModel
    {
        IConverter _converter;

        public IndexModel(IConverter converter)
        {
            _converter = converter;
        }

        public void OnGet()
        {
            var doc = new HtmlToPdfDocument()
            {
                GlobalSettings = {
                    ColorMode = ColorMode.Color,
                    Orientation = Orientation.Landscape,
                    PaperSize = PaperKind.A4Plus,
                },
                            Objects = {
                    new ObjectSettings() {
                        PagesCount = true,
                        HtmlContent = @"Lorem ipsum dolor sit amet, consectetur adipiscing elit. In consectetur mauris eget ultrices  iaculis. Ut                               odio viverra, molestie lectus nec, venenatis turpis.",
                        WebSettings = { DefaultEncoding = "utf-8" },
                        HeaderSettings = { FontSize = 9, Right = "Page [page] of [toPage]", Line = true, Spacing = 2.812 }
                    }
                }
            };

            var result = _converter.Convert(doc);
        }
    }
```

**Comment by Ahmed-Raouf** [comment] 2018-01-29 04:45
Thanks For your effort @rdvojmoc

**Comment by rdvojmoc** [comment] 2018-01-29 06:54
Glad that I could help. Closing...

**Closed by rdvojmoc** 2018-01-29 06:54 UTC

**Comment by fabercs** [comment] 2019-03-27 15:07
> Deleted directory `/bin` and `/obj`, then compiled and started again and get no error. After trying to convert a file in `Index.cs.html` I get error `BadImageFormatException: Image is either too small or contains an invalid byte offset or count.` which was was caused because wrong `libwkhtmltox` libraries (only 48 kB in size). After replacing the libraries I successfuly converted a file in `Index.cs.html`. Code:

I am having the same issue..
I did not understand, what should be the actual size of the native 64bit library? I downloaded from [here](https://github.com/rdvojmoc/DinkToPdf/tree/master/v0.12.4/64%20bit) and it is `57kb`. Where could I find the proper dlls?

**Comment by fabercs** [comment] 2019-03-27 15:20
I didn't uderstand why or how, but I downloaded the dll from the location via right click and "save file as.." opiton. This seems download the file, but broken I guess. I downloaded it again by 
 1- clicking on the dll file (`libwkhtmltox`), 
 2- get related page and on page click download button.

This gets downloaded the actual (_larger_) dll.

**Comment by BvdVen** [comment] 2019-11-01 12:59
@fabercs Thats the same problem I've had. I had the small files because I (apparently) downloaded 'wrong'.
